### PR TITLE
search filters

### PR DESCRIPTION
**Pull request by mscoutermarsh**
Have search filters started. About halfway there.

see: http://li245-46.members.linode.com/

### CODE REVIEW

**Comment by coderintherye** [comment]
Currently, it looks like the cookie isn't get set, cause I get an error in the JS, that allFilters is null. I'll try running on my local though to see what happens, might just be my browser setup.

**Comment by mscoutermarsh** [comment]
Oops. Never tested with my cookies wiped out. :-)

I'll fix that. Thanks.

**Comment by mscoutermarsh** [comment]
Alright. That's fixed.

http://li245-46.members.linode.com/

**Comment by mscoutermarsh** [comment]
Copied over to github pages :-)

http://mscoutermarsh.github.com/Kivabeta/

**Comment by coderintherye** [comment]
Sweet!

Just an FYI, we have branch cut on Wednesday, so I'm going to be struggling
to make that on time, afterwards I'll be back to interacting and reviewing.
Thanks for your work on this :)

-k

On Mon, May 7, 2012 at 7:05 PM, Mike Coutermarsh <
reply@reply.github.com

**Pull request merged**
